version: 0.2
phases:
   install:
     runtime-versions:
         php: 8.0
         nodejs: 12.x
     commands:
         - apt-get update -y
         - apt-get install -y libpq-dev libzip-dev
         - apt-get install -y php-pgsql
         - curl -sS <https://getcomposer.org/installer> | php -- --install-dir=/usr/local/bin --filename=composer
   pre_build:
     commands:
         - php -r "file_exists('.env') || copy('.env.example', '.env');"
         - composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
         - npm install
   build:
     commands:
         - npm run production
         - php artisan migrate --force
         - php artisan db:seed
artifacts:
   files:
         - '**/*'
   name: $(date +%Y-%m-%dT%H:%M:%S).zip
proxy:
   upload-artifacts: yes
   logs: yes